### ISSUE TITLE
How to store tagger field to column SQL table when the name is different?

### ISSUE THREAD

**Issue by LeMoussel** [Norconex/committer-sql#7]
In `createTableSQL` Tag, I can set the fields that are available for the tagger. I.E. the fields that would go here:

``` xml
<tagger class="com.norconex.importer.handler.tagger.impl.KeepOnlyTagger">
    <fields>title,description,document.reference,google-site-verification</fields>
/tagger>
```

The fields obtained vary for each document/site. I use [DebugTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/DebugTagger.html) to list them.

I create a table like this :
``` sql
CREATE TABLE ${tableName} (
      ${targetReferenceField} VARCHAR(32672) NOT NULL, 
      ${targetContentField}  CLOB, 
      title VARCHAR(256),
      description VARCHAR(256),
      googleSiteVerification VARCHAR(256),
      PRIMARY KEY ( ${targetReferenceField} )
  )
```
How to match `google-site-verification` tagger field to `googleSiteVerification `column`?

**Comment by LeMoussel** [comment]
is the solution to use [RenameTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/RenameTagger.html) tag?

Like this:
``` xml
<tagger class="com.norconex.importer.handler.tagger.impl.RenameTagger">
   <rename fromField="google-site-verification" toField="googleSiteVerification " overwrite="true"/>
</tagger>
```

**Comment by essiembre** [comment]
Rename Tagger should do it.  Please confirm.

**Comment by LeMoussel** [comment]
Yes. It's OK.
